#!/usr/bin/env bash
# script desplays "To infinity and beyond" infinitly with a sleep 2
# "I am invincible!!!" when receiving a SIGTERM signal

remove_and_quit()
{
    rm -f /var/run/holbertonscript.pid;
    exit
}
trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'; remove_and_quit" SIGTERM
trap "echo 'I hate the kill command'; remove_and_quit" SIGQUIT

echo $$ >> /var/run/myscript.pid
while true; do
	echo "To infinity and beyond"
	sleep 2
done
