#!/usr/bin/env bash
# Start/Stops/Restarts

argv1=$1
tmpfile="/var/run/my_process.pid"

startLoop()
{
	./manage_my_process &
	echo "$!" > "$tmpfile"
}
killLoop()
{
	sudo pkill -f "./manage_my_process"
	rm -r /var/run/my_process.pid
}
case "$argv1" in
	start) echo "manage_my_process started"
		startLoop
		;;
	stop) echo "manage_my_process stopped"
		killLoop
		;;
	restart) echo "manage_my_process restarted"
		killLoop
		startLoop
		;;
	*) echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
