#!/usr/bin/env bash
# Script displays number fro 1 to 100
# displays Fizz for a multiple of 3
# Buzz for a multiple of 5 and FizzBuzz for multiple of both

for i in {1..100}; do
	if ((( i % 3) == 0 && (i % 5) == 0 )); then
		echo "FizzBuzz"
	elif (( i % 3 == 0 )); then
		echo "Fizz"
	elif (( i % 5 == 0)); then
		echo "Buzz"
	else
		echo "$i"
	fi
done
