#!/usr/bin/env bash
# Script updates hostfile to change local host to 127.0.0.2 and facebook.com to 8.8.8.8

cp /etc/hosts hosts_tmp
sed -i s/127.*$/127.0.0.2\\tlocalhost\\n8.8.8.8\\tfacebook.com/g hosts_tmp
cp -f hosts_tmp /etc/hosts
